export const iconPaths = {
  hamburger: "/icons/svg/hamburger.svg",
  bell: "/icons/svg/bell.svg",
  profile: "/icons/svg/user.svg",
  search: "/icons/svg/search.svg",
  logout: "/icons/svg/logout.svg",
  add: "/icons/svg/add.svg",
  "sidebar.dashboard.base": "/icons/svg/sidebar/home.svg",
  "sidebar.dashboard.active": "/icons/svg/sidebar/home-active.svg",
  "sidebar.vendor.base": "/icons/svg/sidebar/vendor.svg",
  "sidebar.vendor.active": "/icons/svg/sidebar/vendor-active.svg",
  "sidebar.rider.base": "/icons/svg/sidebar/rider.svg",
  "sidebar.rider.active": "/icons/svg/sidebar/rider-active.svg",
  "sidebar.product.base": "/icons/svg/sidebar/product.svg",
  "sidebar.product.active": "/icons/svg/sidebar/product-active.svg",
  "sidebar.customer.base": "/icons/svg/sidebar/customer.svg",
  "sidebar.customer.active": "/icons/svg/sidebar/customer-active.svg",
  "sidebar.order.base": "/icons/svg/sidebar/order.svg",
  "sidebar.order.active": "/icons/svg/sidebar/order-active.svg",
  "sidebar.errand.base": "/icons/svg/sidebar/errand.svg",
  "sidebar.errand.active": "/icons/svg/sidebar/errand-active.svg",
  "sidebar.transaction.base": "/icons/svg/sidebar/transaction.svg",
  "sidebar.transaction.active": "/icons/svg/sidebar/transaction-active.svg",
  "sidebar.metrics.base": "/icons/svg/sidebar/metrics.svg",
  "sidebar.metrics.active": "/icons/svg/sidebar/metrics-active.svg",
};
